Add fees docs
KlimaDAO/carbonmark-docs pull request #3
Opened 2023-07-28 01:32 UTC by Atmosfearful

Preview here

https://github.com/KlimaDAO/carbonmark-docs/blob/add-fees-docs/resources/fees.md

2023-07-28 11:46 UTC, jabby09 requested changes
@ChazSchmidt make sure you double check the math on the total total network fee column, I think in a few places we lost the 1%

"No network fees." does not need the "." at the end

> It is completely free to purchase or retire carbon from a seller listing with USDC. You can also create and manage your own listings at zero additional cost.

While true this feature is currently turned off so we should make mention of that somehow or else the user will start off confused from the beginning. 

> *Network fees depend on purchase type, not payment method.

add (see below) after purchase type

> As shown in the table above, when you pay with payment processing partners...

Should read "As shown in the table above, when you pay with credit card our payment processing partners..."

2023-07-28 15:30 UTC, Atmosfearful commented
Good finds, fixed!

2023-07-28 19:15 UTC, jabby09 approved these changes

2023-07-31 21:44 UTC, Atmosfearful commented
Merged in 9f6db4fe328b885a40c358f772a15cd31fb71bf5

2023-07-31 21:44 UTC, closed without merging